version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7777
      - ASPNETCORE_HTTPS_PORTS=80
    ports:
      - "7777:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  client:
    ports:
      - "5173:3000"

  proxy: 
    volumes:
      - ./nginx/conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"